apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tier3-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: tier3
  source:
    repoURL: "https://github.com/REPLACE_ME/full-fledge.git"
    targetRevision: main
    path: k8s/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: tier3-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
