apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tier3
  namespace: argocd
spec:
  description: 3-tier production application
  sourceRepos:
    - "https://github.com/REPLACE_ME/full-fledge.git"
  destinations:
    - server: https://kubernetes.default.svc
      namespace: tier3
    - server: https://kubernetes.default.svc
      namespace: tier3-staging
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
