apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tier3

resources:
  - namespace.yaml
  - config.yaml
  - database.yaml
  - backend.yaml
  - frontend.yaml
  - ingress.yaml
  - networkpolicy.yaml

commonLabels:
  app.kubernetes.io/part-of: tier3

images:
  - name: backend
    newName: REGION-docker.pkg.dev/PROJECT/tier3-gke-images/backend
    newTag: latest
  - name: frontend
    newName: REGION-docker.pkg.dev/PROJECT/tier3-gke-images/frontend
    newTag: latest
